site_name: "chart.xkcd Documentation"
docs_dir: pages
site_dir: docs

theme:
  name: material

nav:
- Home: index.md
- Software:
  - bar.md
  - line.md
  - pie.md
  - radar.md
  - renderer.md
  - scatter.md
  - stacked_bar.md
- Project:
  - license.md
  - conduct.md
  - contributing.md

plugins:
- mkdocstrings:
    handlers:
      python:
        paths:
          - src

markdown_extensions:
- pymdownx.highlight
- pymdownx.superfences

exclude_docs: >
  *~
